USE [master]
GO
/****** Object:  Database [YOURDBNAME]    
чтобы создать свобю БД надо заменить [YOURDBNAME] на имя своей БД и запустить скрипт

******/
CREATE DATABASE [YOURDBNAME]
 CONTAINMENT = NONE
GO
ALTER DATABASE [YOURDBNAME] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [YOURDBNAME].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [YOURDBNAME] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [YOURDBNAME] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [YOURDBNAME] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [YOURDBNAME] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [YOURDBNAME] SET ARITHABORT OFF 
GO
ALTER DATABASE [YOURDBNAME] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [YOURDBNAME] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [YOURDBNAME] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [YOURDBNAME] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [YOURDBNAME] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [YOURDBNAME] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [YOURDBNAME] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [YOURDBNAME] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [YOURDBNAME] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [YOURDBNAME] SET  DISABLE_BROKER 
GO
ALTER DATABASE [YOURDBNAME] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [YOURDBNAME] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [YOURDBNAME] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [YOURDBNAME] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [YOURDBNAME] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [YOURDBNAME] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [YOURDBNAME] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [YOURDBNAME] SET RECOVERY FULL 
GO
ALTER DATABASE [YOURDBNAME] SET  MULTI_USER 
GO
ALTER DATABASE [YOURDBNAME] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [YOURDBNAME] SET DB_CHAINING OFF 
GO
ALTER DATABASE [YOURDBNAME] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [YOURDBNAME] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [YOURDBNAME] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [YOURDBNAME] SET QUERY_STORE = OFF
GO
USE [YOURDBNAME]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [YOURDBNAME]
GO
/****** Object:  Table [dbo].[Actions]    Script Date: 27.12.2021 16:22:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Actions](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](256) NULL,
	[Descr] [nvarchar](1000) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ApiEvents]    Script Date: 27.12.2021 16:22:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ApiEvents](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NULL,
	[ImeiId] [int] NULL,
	[DateTime] [datetime] NULL,
	[Type] [nvarchar](500) NULL,
	[Message] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ApiRequests]    Script Date: 27.12.2021 16:22:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ApiRequests](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Guid] [nvarchar](500) NULL,
	[Body] [nvarchar](max) NULL,
	[Date] [datetime] NULL,
	[Status] [int] NULL,
	[Descr] [nvarchar](1000) NULL,
	[UserId] [int] NOT NULL,
	[ImeiId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_ApiRequests_unique] UNIQUE NONCLUSTERED 
(
	[Guid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ApiSettings]    Script Date: 27.12.2021 16:22:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ApiSettings](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Type] [nvarchar](500) NULL,
	[Value] [nvarchar](1500) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Imeis]    Script Date: 27.12.2021 16:22:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Imeis](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Imei] [nvarchar](256) NULL,
	[Descr] [nvarchar](1000) NULL,
	[IsActive] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_Imei_unique] UNIQUE NONCLUSTERED 
(
	[Imei] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Menus]    Script Date: 27.12.2021 16:22:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Menus](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](256) NULL,
	[action] [nvarchar](256) NULL,
	[Descr] [nvarchar](1000) NULL,
	[Npp] [int] NOT NULL,
 CONSTRAINT [PK__Menus__3214EC279DF13BCF] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Role_Menu]    Script Date: 27.12.2021 16:22:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Role_Menu](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[roleID] [int] NOT NULL,
	[menuID] [int] NOT NULL,
	[Descr] [nvarchar](1000) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_RoleMenu_unique] UNIQUE NONCLUSTERED 
(
	[roleID] ASC,
	[menuID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 27.12.2021 16:22:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](500) NULL,
	[Descr] [nvarchar](1000) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Service_Users]    Script Date: 27.12.2021 16:22:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Service_Users](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[createDate] [date] NULL,
	[login] [nvarchar](256) NULL,
	[password] [nvarchar](256) NULL,
	[Descr] [nvarchar](1000) NULL,
	[IsAdmin] [bit] NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Settings]    Script Date: 27.12.2021 16:22:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Settings](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[type] [nvarchar](256) NULL,
	[name] [nvarchar](256) NULL,
	[value] [nvarchar](256) NULL,
 CONSTRAINT [PK__ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User_Imei]    Script Date: 27.12.2021 16:22:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User_Imei](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[imeiId] [int] NOT NULL,
	[userID] [int] NOT NULL,
	[CreateDate] [datetime] NULL,
	[Descr] [nvarchar](1000) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_UserImei_unique] UNIQUE NONCLUSTERED 
(
	[userID] ASC,
	[imeiId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User_Roles]    Script Date: 27.12.2021 16:22:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User_Roles](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[userID] [int] NOT NULL,
	[roleId] [int] NOT NULL,
	[GiveDate] [datetime] NULL,
	[Descr] [nvarchar](1000) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_UserRole_unique] UNIQUE NONCLUSTERED 
(
	[userID] ASC,
	[roleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User_Tokens]    Script Date: 27.12.2021 16:22:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User_Tokens](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[userID] [int] NOT NULL,
	[imeiId] [int] NOT NULL,
	[token] [nvarchar](256) NULL,
	[CreateDate] [datetime] NULL,
	[ExpireDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [LoginUnique]    Script Date: 27.12.2021 16:22:04 ******/
CREATE UNIQUE NONCLUSTERED INDEX [LoginUnique] ON [dbo].[Service_Users]
(
	[login] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [NameUnique]    Script Date: 27.12.2021 16:22:04 ******/
CREATE UNIQUE NONCLUSTERED INDEX [NameUnique] ON [dbo].[Settings]
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Imeis] ADD  CONSTRAINT [DF_Imeis_IsActive]  DEFAULT ((0)) FOR [IsActive]
GO
ALTER TABLE [dbo].[ApiEvents]  WITH CHECK ADD FOREIGN KEY([ImeiId])
REFERENCES [dbo].[Imeis] ([ID])
GO
ALTER TABLE [dbo].[ApiEvents]  WITH CHECK ADD  CONSTRAINT [FK__ApiEvents__UserI__2CF2ADDF] FOREIGN KEY([UserId])
REFERENCES [dbo].[Service_Users] ([ID])
GO
ALTER TABLE [dbo].[ApiEvents] CHECK CONSTRAINT [FK__ApiEvents__UserI__2CF2ADDF]
GO
ALTER TABLE [dbo].[ApiRequests]  WITH CHECK ADD FOREIGN KEY([ImeiId])
REFERENCES [dbo].[Imeis] ([ID])
GO
ALTER TABLE [dbo].[ApiRequests]  WITH CHECK ADD  CONSTRAINT [FK__ApiReques__UserI__245D67DE] FOREIGN KEY([UserId])
REFERENCES [dbo].[Service_Users] ([ID])
GO
ALTER TABLE [dbo].[ApiRequests] CHECK CONSTRAINT [FK__ApiReques__UserI__245D67DE]
GO
ALTER TABLE [dbo].[Role_Menu]  WITH CHECK ADD  CONSTRAINT [FK__Role_Menu__menuI__6B24EA82] FOREIGN KEY([menuID])
REFERENCES [dbo].[Menus] ([ID])
GO
ALTER TABLE [dbo].[Role_Menu] CHECK CONSTRAINT [FK__Role_Menu__menuI__6B24EA82]
GO
ALTER TABLE [dbo].[Role_Menu]  WITH CHECK ADD FOREIGN KEY([roleID])
REFERENCES [dbo].[Roles] ([ID])
GO
ALTER TABLE [dbo].[User_Imei]  WITH CHECK ADD FOREIGN KEY([imeiId])
REFERENCES [dbo].[Imeis] ([ID])
GO
ALTER TABLE [dbo].[User_Imei]  WITH CHECK ADD  CONSTRAINT [FK__User_Imei__userI__5CD6CB2B] FOREIGN KEY([userID])
REFERENCES [dbo].[Service_Users] ([ID])
GO
ALTER TABLE [dbo].[User_Imei] CHECK CONSTRAINT [FK__User_Imei__userI__5CD6CB2B]
GO
ALTER TABLE [dbo].[User_Roles]  WITH CHECK ADD FOREIGN KEY([roleId])
REFERENCES [dbo].[Roles] ([ID])
GO
ALTER TABLE [dbo].[User_Roles]  WITH CHECK ADD  CONSTRAINT [FK__User_Role__userI__60A75C0F] FOREIGN KEY([userID])
REFERENCES [dbo].[Service_Users] ([ID])
GO
ALTER TABLE [dbo].[User_Roles] CHECK CONSTRAINT [FK__User_Role__userI__60A75C0F]
GO
ALTER TABLE [dbo].[User_Tokens]  WITH CHECK ADD FOREIGN KEY([imeiId])
REFERENCES [dbo].[Imeis] ([ID])
GO
ALTER TABLE [dbo].[User_Tokens]  WITH CHECK ADD  CONSTRAINT [FK__User_Toke__userI__09A971A2] FOREIGN KEY([userID])
REFERENCES [dbo].[Service_Users] ([ID])
GO
ALTER TABLE [dbo].[User_Tokens] CHECK CONSTRAINT [FK__User_Toke__userI__09A971A2]
GO
USE [master]
GO
ALTER DATABASE [YOURDBNAME] SET  READ_WRITE 
GO

/****** Script for SelectTopNRows command from SSMS  ******/
use [YOURDBNAME] 

insert Service_Users ([createDate],[login],[password],[Descr],[IsAdmin],[IsActive]) values  (getdate(), 'Admin', '', 'builtInAdmin', 'True', 'True')

Insert Settings ( [type], [name], [value]) values('bool', 'LinkImeiUser', '+')
Insert Settings ( [type], [name], [value]) values('int', 'LifeTimeToken', '300')
Insert Settings ( [type], [name], [value]) values('nvarchar(500)', 'ESB_GetObjectById', 'http://<SERVER:PORT>/api/Atlantis/GetObjectByIdentifier')
Insert Settings ( [type], [name], [value]) values('nvarchar(500)', 'ESB_ExecOperation', 'http://<SERVER:PORT>/api/Atlantis/ExecuteRequest')
Insert Settings ( [type], [name], [value]) values('nvarchar(500)', 'ESB_ExecOperationAsync', 'http://<SERVER:PORT>/api/Atlantis/ExecuteOperation')
Insert Settings ( [type], [name], [value]) values('nvarchar(500)', 'ESB_GetDescrShk', 'http://<SERVER:PORT>/api/Atlantis/GetDescriptionShk')
