// Autogenerated file
using System.Reflection;

#pragma warning disable 0436
#if SKIPPRODUCTINFO
#else
[assembly: AssemblyProduct(ProductInfo.AssemblyProduct)]
[assembly: AssemblyCopyright(ProductInfo.AssemblyCopyright)]
[assembly: AssemblyTrademark(ProductInfo.AssemblyTrademark)]
[assembly: AssemblyCompany(ProductInfo.AssemblyCompany)]
[assembly: AssemblyVersion(ProductInfo.AssemblyVersion)]
[assembly: AssemblyFileVersion(ProductInfo.AssemblyFileVersion)]
#endif

partial class ProductInfo
{
    public const string AssemblyProduct = "Galaktika.ESB";
    public const string AssemblyCopyright = "Galaktika 2018";
    public const string AssemblyTrademark = "Xafari";
    public const string AssemblyCompany = "Galaktika";
    public const string AssemblyFileVersion = "2.3.3.1170";
    public const string AssemblyVersion = "2.3.3.1170";
    public const string MajorMinorVersion = "2.3";
    public const string SpecificBuildNumber = "1";
}
#pragma warning restore 0436
