//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSD {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSD.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --BATCH--.
        /// </summary>
        public static string BatchLoad {
            get {
                return ResourceManager.GetString("BatchLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string ConstCancel {
            get {
                return ResourceManager.GetString("ConstCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на application/json.
        /// </summary>
        public static string ContentTypeJson {
            get {
                return ResourceManager.GetString("ContentTypeJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b1f310e2231b63bf5a9b4f9e985d973a5ab5eb8e02293aa36d4eb3bffd085fbf.
        /// </summary>
        public static string DefaultHashPassword {
            get {
                return ResourceManager.GetString("DefaultHashPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на actions/.
        /// </summary>
        public static string GetActions {
            get {
                return ResourceManager.GetString("GetActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход по штрих-коду.
        /// </summary>
        public static string LabelSwitchBarcode {
            get {
                return ResourceManager.GetString("LabelSwitchBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход по логину и паролю.
        /// </summary>
        public static string LabelSwitchUserPass {
            get {
                return ResourceManager.GetString("LabelSwitchUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поступление МЦ.
        /// </summary>
        public static string MenuAdmissionMC {
            get {
                return ResourceManager.GetString("MenuAdmissionMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутреннее перемещение.
        /// </summary>
        public static string MenuInternalDisplacement {
            get {
                return ResourceManager.GetString("MenuInternalDisplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инвентаризация.
        /// </summary>
        public static string MenuInventory {
            get {
                return ResourceManager.GetString("MenuInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отпуск со склада.
        /// </summary>
        public static string MenuIssueFromTheWarehouse {
            get {
                return ResourceManager.GetString("MenuIssueFromTheWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размещение на место хранения.
        /// </summary>
        public static string MenuPlacementInStorage {
            get {
                return ResourceManager.GetString("MenuPlacementInStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль администратора был успешно изменен!.
        /// </summary>
        public static string MessageAcceptPass {
            get {
                return ResourceManager.GetString("MessageAcceptPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на недоступен для подключения, попробуйте другой адрес.
        /// </summary>
        public static string MessageAddressNotWork {
            get {
                return ResourceManager.GetString("MessageAddressNotWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно авторизоваться, так как нет доступа к сети.
        /// </summary>
        public static string MessageAuthNotInternet {
            get {
                return ResourceManager.GetString("MessageAuthNotInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пакетная загрузка.
        /// </summary>
        public static string MessageBatchSelect {
            get {
                return ResourceManager.GetString("MessageBatchSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для начала выберите документ.
        /// </summary>
        public static string MessageBeginSelectDoc {
            get {
                return ResourceManager.GetString("MessageBeginSelectDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Позиция заблокирована для обработки.
        /// </summary>
        public static string MessageBlockPositionSession {
            get {
                return ResourceManager.GetString("MessageBlockPositionSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сеть отсутствует, а записей о текущих документах в локальной БД отсутствует, дальнейшая работа невозможна.
        /// </summary>
        public static string MessageBlockWork {
            get {
                return ResourceManager.GetString("MessageBlockWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистка БД успешно завершена..
        /// </summary>
        public static string MessageClearDBSuccess {
            get {
                return ResourceManager.GetString("MessageClearDBSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключение к серверу неактивно, проверьте строку подключения или подключение к сети.
        /// </summary>
        public static string MessageConnectStringFail {
            get {
                return ResourceManager.GetString("MessageConnectStringFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В локальной базе данных документы отсутствую.
        /// </summary>
        public static string MessageDataBaseMultiNoDoc {
            get {
                return ResourceManager.GetString("MessageDataBaseMultiNoDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В локальной БД не обнаружен документ с таким идентификатором.
        /// </summary>
        public static string MessageDataBaseNoDoc {
            get {
                return ResourceManager.GetString("MessageDataBaseNoDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В локальной БД.
        /// </summary>
        public static string MessageDataBaseSelect {
            get {
                return ResourceManager.GetString("MessageDataBaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на База данных пуста, удалять нечего....
        /// </summary>
        public static string MessageEmptyByDelete {
            get {
                return ResourceManager.GetString("MessageEmptyByDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключение недоступно, произошло переподключение по адресу.
        /// </summary>
        public static string MessageErrorAddress {
            get {
                return ResourceManager.GetString("MessageErrorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время сессии истекло.
        /// </summary>
        public static string MessageExpires {
            get {
                return ResourceManager.GetString("MessageExpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Через идентификатор.
        /// </summary>
        public static string MessageIdentificatorSelect {
            get {
                return ResourceManager.GetString("MessageIdentificatorSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверно введен пароль администратора!.
        /// </summary>
        public static string MessageInvalidPassAdmin {
            get {
                return ResourceManager.GetString("MessageInvalidPassAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сеть не доступна и в справочнике не найден элемент.
        /// </summary>
        public static string MessageNoNetAndDictionaryEmpty {
            get {
                return ResourceManager.GetString("MessageNoNetAndDictionaryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизация не пройдена.
        /// </summary>
        public static string MessageNotAuth {
            get {
                return ResourceManager.GetString("MessageNotAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пароль не совпадает с подтверждением!.
        /// </summary>
        public static string MessageNotConfirmPass {
            get {
                return ResourceManager.GetString("MessageNotConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проблема с подключением...Попробуйте позднее.
        /// </summary>
        public static string MessageNotConnect {
            get {
                return ResourceManager.GetString("MessageNotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Так как нет соединения, операция над документом будет выполнена позже.
        /// </summary>
        public static string MessageNotNet {
            get {
                return ResourceManager.GetString("MessageNotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует подключение к сети....
        /// </summary>
        public static string MessageNotNetwork {
            get {
                return ResourceManager.GetString("MessageNotNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пароль не введён!.
        /// </summary>
        public static string MessageNotNewPass {
            get {
                return ResourceManager.GetString("MessageNotNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введёный пароль не совпадает с текущим паролем!.
        /// </summary>
        public static string MessageNotOldPass {
            get {
                return ResourceManager.GetString("MessageNotOldPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле ввода пароля не может быть пустым!.
        /// </summary>
        public static string MessageNotPasswordAdmin {
            get {
                return ResourceManager.GetString("MessageNotPasswordAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо установить пароль администратора!.
        /// </summary>
        public static string MessageNotPasswordAdminManager {
            get {
                return ResourceManager.GetString("MessageNotPasswordAdminManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступ к Imei запрещён.
        /// </summary>
        public static string MessagePermissionErrorImei {
            get {
                return ResourceManager.GetString("MessagePermissionErrorImei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить ВСЕ документы?.
        /// </summary>
        public static string MessageQuestionDeleteAllDoc {
            get {
                return ResourceManager.GetString("MessageQuestionDeleteAllDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить документ?.
        /// </summary>
        public static string MessageQuestionDeleteDoc {
            get {
                return ResourceManager.GetString("MessageQuestionDeleteDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите выйти?.
        /// </summary>
        public static string MessageQuestionLogout {
            get {
                return ResourceManager.GetString("MessageQuestionLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный документ уже загружен в локальную базу данных? Хотите загрузить снова?.
        /// </summary>
        public static string MessageQuestionRepeatDownloadDoc {
            get {
                return ResourceManager.GetString("MessageQuestionRepeatDownloadDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошел выход из системы, так как токен просрочен. Выполните повторный вход.
        /// </summary>
        public static string MessageRepeatAuth {
            get {
                return ResourceManager.GetString("MessageRepeatAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки сохранены!.
        /// </summary>
        public static string MessageSaveSetting {
            get {
                return ResourceManager.GetString("MessageSaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данная позиция уже просматривалась! Хотите продолжить?.
        /// </summary>
        public static string MessageSeeRepeatPosition {
            get {
                return ResourceManager.GetString("MessageSeeRepeatPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите документ.
        /// </summary>
        public static string MessageSelectDoc {
            get {
                return ResourceManager.GetString("MessageSelectDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите документ из списка.
        /// </summary>
        public static string MessageSelectDocInList {
            get {
                return ResourceManager.GetString("MessageSelectDocInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В предыдущем сеансе работы приложения произошел сбой, приносим извинения за предоставленные неудобства, наши специалисты уже решают проблему....
        /// </summary>
        public static string MessageSessionCrash {
            get {
                return ResourceManager.GetString("MessageSessionCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление позиции....
        /// </summary>
        public static string MessageStatusAddPosition {
            get {
                return ResourceManager.GetString("MessageStatusAddPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение запроса...Ожидайте.
        /// </summary>
        public static string MessageStatusComplitingQuery {
            get {
                return ResourceManager.GetString("MessageStatusComplitingQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление документа....
        /// </summary>
        public static string MessageStatusDeleteDoc {
            get {
                return ResourceManager.GetString("MessageStatusDeleteDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка....
        /// </summary>
        public static string MessageStatusLoading {
            get {
                return ResourceManager.GetString("MessageStatusLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка меню....
        /// </summary>
        public static string MessageStatusLoadingMenu {
            get {
                return ResourceManager.GetString("MessageStatusLoadingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение синхронной операции....
        /// </summary>
        public static string MessageStatusSyncOperation {
            get {
                return ResourceManager.GetString("MessageStatusSyncOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки сохранены.
        /// </summary>
        public static string MessageTagFullSaveSetting {
            get {
                return ResourceManager.GetString("MessageTagFullSaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес подключения не  действителен и не будет сохранен. Остальные настройки успешно изменены.
        /// </summary>
        public static string MessageTagPartialSaveSetting {
            get {
                return ResourceManager.GetString("MessageTagPartialSaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для продолжения работы в ТСД, необходимо разрешить приложению доступ к информации устройства..
        /// </summary>
        public static string MessageTextPermissonPhone {
            get {
                return ResourceManager.GetString("MessageTextPermissonPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данная позиция отсутствует в этом документе.
        /// </summary>
        public static string MessageUnFoundPosition {
            get {
                return ResourceManager.GetString("MessageUnFoundPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Непредвиденная ошибка....
        /// </summary>
        public static string MessageUnknownError {
            get {
                return ResourceManager.GetString("MessageUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная ошибка, запрос не прошел.
        /// </summary>
        public static string MessageUnknownErrorQuery {
            get {
                return ResourceManager.GetString("MessageUnknownErrorQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строка адреса не заполнена. Попытка подключения невозможна.
        /// </summary>
        public static string MessageUnknownHostPort {
            get {
                return ResourceManager.GetString("MessageUnknownHostPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбран элемент меню.
        /// </summary>
        public static string MessageUnSelectMenu {
            get {
                return ResourceManager.GetString("MessageUnSelectMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новые данные успешно загружены....
        /// </summary>
        public static string MessageUpdateNewDoc {
            get {
                return ResourceManager.GetString("MessageUpdateNewDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Токен обновлён.
        /// </summary>
        public static string MessageUpdateToken {
            get {
                return ResourceManager.GetString("MessageUpdateToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные успешно выгружены.
        /// </summary>
        public static string MessageUploadData {
            get {
                return ResourceManager.GetString("MessageUploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные успешно выгружены, документ будет закрыт и удален.
        /// </summary>
        public static string MessageUploadDataWithCloseDoc {
            get {
                return ResourceManager.GetString("MessageUploadDataWithCloseDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос вернул необработанную ошибку, проверьте работу ACTION:.
        /// </summary>
        public static string MessageWarinigNullResponseAction {
            get {
                return ResourceManager.GetString("MessageWarinigNullResponseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данная позиция обработана, вы действительно хотите продолжить? Внимание, редактируемые данные обнулятся.
        /// </summary>
        public static string MessageWarningPositionBlockContinue {
            get {
                return ResourceManager.GetString("MessageWarningPositionBlockContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Позиция добавлена.
        /// </summary>
        public static string MsgCenterTagAddPosition {
            get {
                return ResourceManager.GetString("MsgCenterTagAddPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BlockToolbar.
        /// </summary>
        public static string MsgCenterTagBlockToolbar {
            get {
                return ResourceManager.GetString("MsgCenterTagBlockToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CancelSearch.
        /// </summary>
        public static string MsgCenterTagCancelSearch {
            get {
                return ResourceManager.GetString("MsgCenterTagCancelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CancelView.
        /// </summary>
        public static string MsgCenterTagCancelView {
            get {
                return ResourceManager.GetString("MsgCenterTagCancelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CloseContentDialog.
        /// </summary>
        public static string MsgCenterTagCloseContentDialog {
            get {
                return ResourceManager.GetString("MsgCenterTagCloseContentDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CloseDetail.
        /// </summary>
        public static string MsgCenterTagCloseDetail {
            get {
                return ResourceManager.GetString("MsgCenterTagCloseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CloseDetailWithDeleteRow.
        /// </summary>
        public static string MsgCenterTagCloseDetailWithDelete {
            get {
                return ResourceManager.GetString("MsgCenterTagCloseDetailWithDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CloseHamburger.
        /// </summary>
        public static string MsgCenterTagCloseHamburger {
            get {
                return ResourceManager.GetString("MsgCenterTagCloseHamburger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DefaultPage.
        /// </summary>
        public static string MsgCenterTagDefaultPage {
            get {
                return ResourceManager.GetString("MsgCenterTagDefaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GestureFlyout.
        /// </summary>
        public static string MsgCenterTagGestureFlyout {
            get {
                return ResourceManager.GetString("MsgCenterTagGestureFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IsEnabledView.
        /// </summary>
        public static string MsgCenterTagIsEnabledView {
            get {
                return ResourceManager.GetString("MsgCenterTagIsEnabledView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IsExistBarcode.
        /// </summary>
        public static string MsgCenterTagIsExistBarcode {
            get {
                return ResourceManager.GetString("MsgCenterTagIsExistBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IsOpenDetail.
        /// </summary>
        public static string MsgCenterTagIsOpenDetail {
            get {
                return ResourceManager.GetString("MsgCenterTagIsOpenDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IsVisibleHomeUpdate.
        /// </summary>
        public static string MsgCenterTagIsVisibleHomeUpdate {
            get {
                return ResourceManager.GetString("MsgCenterTagIsVisibleHomeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading.
        /// </summary>
        public static string MsgCenterTagLoading {
            get {
                return ResourceManager.GetString("MsgCenterTagLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LoadingView.
        /// </summary>
        public static string MsgCenterTagLoadingView {
            get {
                return ResourceManager.GetString("MsgCenterTagLoadingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string MsgCenterTagLogin {
            get {
                return ResourceManager.GetString("MsgCenterTagLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        public static string MsgCenterTagLogout {
            get {
                return ResourceManager.GetString("MsgCenterTagLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MenuLoad.
        /// </summary>
        public static string MsgCenterTagMenuLoad {
            get {
                return ResourceManager.GetString("MsgCenterTagMenuLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network.
        /// </summary>
        public static string MsgCenterTagNetwork {
            get {
                return ResourceManager.GetString("MsgCenterTagNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OpenDetail.
        /// </summary>
        public static string MsgCenterTagOpenDetail {
            get {
                return ResourceManager.GetString("MsgCenterTagOpenDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OpenTask.
        /// </summary>
        public static string MsgCenterTagOpenTask {
            get {
                return ResourceManager.GetString("MsgCenterTagOpenTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PasteData.
        /// </summary>
        public static string MsgCenterTagPasteData {
            get {
                return ResourceManager.GetString("MsgCenterTagPasteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PasteText.
        /// </summary>
        public static string MsgCenterTagPasteText {
            get {
                return ResourceManager.GetString("MsgCenterTagPasteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SaveDocumentLocal.
        /// </summary>
        public static string MsgCenterTagSaveDocumentLocal {
            get {
                return ResourceManager.GetString("MsgCenterTagSaveDocumentLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scanner.
        /// </summary>
        public static string MsgCenterTagScanner {
            get {
                return ResourceManager.GetString("MsgCenterTagScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ScannerExpire.
        /// </summary>
        public static string MsgCenterTagScannerExpire {
            get {
                return ResourceManager.GetString("MsgCenterTagScannerExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SendBarcode.
        /// </summary>
        public static string MsgCenterTagSendBarcode {
            get {
                return ResourceManager.GetString("MsgCenterTagSendBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SendDataDetailView.
        /// </summary>
        public static string MsgCenterTagSendDataDetailView {
            get {
                return ResourceManager.GetString("MsgCenterTagSendDataDetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SyncRow.
        /// </summary>
        public static string MsgCenterTagSyncRow {
            get {
                return ResourceManager.GetString("MsgCenterTagSyncRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на update.
        /// </summary>
        public static string MsgCenterTagUpdate {
            get {
                return ResourceManager.GetString("MsgCenterTagUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UpdateAction.
        /// </summary>
        public static string MsgCenterTagUpdateAction {
            get {
                return ResourceManager.GetString("MsgCenterTagUpdateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UpdateAppViewModel.
        /// </summary>
        public static string MsgCenterTagUpdateAppViewModel {
            get {
                return ResourceManager.GetString("MsgCenterTagUpdateAppViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UpdateFormLogin.
        /// </summary>
        public static string MsgCenterTagUpdateFormLogin {
            get {
                return ResourceManager.GetString("MsgCenterTagUpdateFormLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UpdateMenus.
        /// </summary>
        public static string MsgCenterTagUpdateMenus {
            get {
                return ResourceManager.GetString("MsgCenterTagUpdateMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UpdateSelect.
        /// </summary>
        public static string MsgCenterTagUpdateSelect {
            get {
                return ResourceManager.GetString("MsgCenterTagUpdateSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UpdateTextSearch.
        /// </summary>
        public static string MsgCenterTagUpdateTextSearch {
            get {
                return ResourceManager.GetString("MsgCenterTagUpdateTextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UpdateToken.
        /// </summary>
        public static string MsgCenterTagUpdateToken {
            get {
                return ResourceManager.GetString("MsgCenterTagUpdateToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UpdateUniversal.
        /// </summary>
        public static string MsgCenterTagUpdateUniversal {
            get {
                return ResourceManager.GetString("MsgCenterTagUpdateUniversal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WaitAuth.
        /// </summary>
        public static string MsgCenterTagWaitAuth {
            get {
                return ResourceManager.GetString("MsgCenterTagWaitAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить задачу.
        /// </summary>
        public static string MsgCenterUpdateTask {
            get {
                return ResourceManager.GetString("MsgCenterUpdateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UpdateTypeTransfer.
        /// </summary>
        public static string MsgCenterUpdateTypeTransfer {
            get {
                return ResourceManager.GetString("MsgCenterUpdateTypeTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить спецификацию?.
        /// </summary>
        public static string MsgQuestionDeleteRow {
            get {
                return ResourceManager.GetString("MsgQuestionDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документ загружен.
        /// </summary>
        public static string MsgResultDocLoad {
            get {
                return ResourceManager.GetString("MsgResultDocLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документы загружены.
        /// </summary>
        public static string MsgResultMultiDocLoad {
            get {
                return ResourceManager.GetString("MsgResultMultiDocLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LocalBaseSync.db3.
        /// </summary>
        public static string NameDataBase {
            get {
                return ResourceManager.GetString("NameDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на След. позиция.
        /// </summary>
        public static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступ к IMEI был запрещён.
        /// </summary>
        public static string NoAccessIMEI {
            get {
                return ResourceManager.GetString("NoAccessIMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сканируйте штрихкод....
        /// </summary>
        public static string PlaceHolderBarcodeScan {
            get {
                return ResourceManager.GetString("PlaceHolderBarcodeScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти....
        /// </summary>
        public static string PlaceHolderSearch {
            get {
                return ResourceManager.GetString("PlaceHolderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пред. позиция.
        /// </summary>
        public static string PrevButton {
            get {
                return ResourceManager.GetString("PrevButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PasswordAdministrator.
        /// </summary>
        public static string RestAdminPass {
            get {
                return ResourceManager.GetString("RestAdminPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Базовый URL.
        /// </summary>
        public static string RestBaseUrl {
            get {
                return ResourceManager.GetString("RestBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хост.
        /// </summary>
        public static string RestHost {
            get {
                return ResourceManager.GetString("RestHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ACTIONBODY.
        /// </summary>
        public static string RestKeyActionBody {
            get {
                return ResourceManager.GetString("RestKeyActionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ActionName.
        /// </summary>
        public static string RestKeyActionName {
            get {
                return ResourceManager.GetString("RestKeyActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на actionName.
        /// </summary>
        public static string RestKeyActionNameLow {
            get {
                return ResourceManager.GetString("RestKeyActionNameLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ACTIONS.
        /// </summary>
        public static string RestKeyActions {
            get {
                return ResourceManager.GetString("RestKeyActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ALLOWADDROWS.
        /// </summary>
        public static string RestKeyAllowAddRows {
            get {
                return ResourceManager.GetString("RestKeyAllowAddRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ALLOWMODIFY.
        /// </summary>
        public static string RestKeyAllowModify {
            get {
                return ResourceManager.GetString("RestKeyAllowModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bearer.
        /// </summary>
        public static string RestKeyAuthentificationBearer {
            get {
                return ResourceManager.GetString("RestKeyAuthentificationBearer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SYS_BARCODE.
        /// </summary>
        public static string RestKeyBarcode {
            get {
                return ResourceManager.GetString("RestKeyBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BATCHLOAD.
        /// </summary>
        public static string RestKeyBatchLoad {
            get {
                return ResourceManager.GetString("RestKeyBatchLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLOCKPROCESSEDROWS.
        /// </summary>
        public static string RestKeyBlockProcessedRows {
            get {
                return ResourceManager.GetString("RestKeyBlockProcessedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на COLUMNS.
        /// </summary>
        public static string RestKeyColumns {
            get {
                return ResourceManager.GetString("RestKeyColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @odata.context.
        /// </summary>
        public static string RestKeyDataContext {
            get {
                return ResourceManager.GetString("RestKeyDataContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на expireDate.
        /// </summary>
        public static string RestKeyExpire {
            get {
                return ResourceManager.GetString("RestKeyExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FIELDS.
        /// </summary>
        public static string RestKeyFields {
            get {
                return ResourceManager.GetString("RestKeyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid.
        /// </summary>
        public static string RestKeyGuid {
            get {
                return ResourceManager.GetString("RestKeyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid.
        /// </summary>
        public static string RestKeyGuidLower {
            get {
                return ResourceManager.GetString("RestKeyGuidLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ident.
        /// </summary>
        public static string RestKeyIdent {
            get {
                return ResourceManager.GetString("RestKeyIdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IDOBJECT.
        /// </summary>
        public static string RestKeyIdObject {
            get {
                return ResourceManager.GetString("RestKeyIdObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на imei.
        /// </summary>
        public static string RestKeyImei {
            get {
                return ResourceManager.GetString("RestKeyImei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ISDOC.
        /// </summary>
        public static string RestKeyIsDoc {
            get {
                return ResourceManager.GetString("RestKeyIsDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на login.
        /// </summary>
        public static string RestKeyLogin {
            get {
                return ResourceManager.GetString("RestKeyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OBJECTACTION.
        /// </summary>
        public static string RestKeyObjectAction {
            get {
                return ResourceManager.GetString("RestKeyObjectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OBJECTDESCRIPTION.
        /// </summary>
        public static string RestKeyObjectDescription {
            get {
                return ResourceManager.GetString("RestKeyObjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OBJECTVALUES.
        /// </summary>
        public static string RestKeyObjectValues {
            get {
                return ResourceManager.GetString("RestKeyObjectValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на password.
        /// </summary>
        public static string RestKeyPassword {
            get {
                return ResourceManager.GetString("RestKeyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RequestBody.
        /// </summary>
        public static string RestKeyRequestBody {
            get {
                return ResourceManager.GetString("RestKeyRequestBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на result.
        /// </summary>
        public static string RestKeyResult {
            get {
                return ResourceManager.GetString("RestKeyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RESULT_CODE.
        /// </summary>
        public static string RestKeyResultCode {
            get {
                return ResourceManager.GetString("RestKeyResultCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        public static string RestKeyResultCodeOne {
            get {
                return ResourceManager.GetString("RestKeyResultCodeOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RESULT_MSG_RUS.
        /// </summary>
        public static string RestKeyResultMsg {
            get {
                return ResourceManager.GetString("RestKeyResultMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RESULT_MSG.
        /// </summary>
        public static string RestKeyResultMsgDescr {
            get {
                return ResourceManager.GetString("RestKeyResultMsgDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на status.
        /// </summary>
        public static string RestKeyStatusLower {
            get {
                return ResourceManager.GetString("RestKeyStatusLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на token.
        /// </summary>
        public static string RestKeyToken {
            get {
                return ResourceManager.GetString("RestKeyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на value.
        /// </summary>
        public static string RestKeyValue {
            get {
                return ResourceManager.GetString("RestKeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ с сервера отсутствует, операция прекращена.
        /// </summary>
        public static string RestMessageAnswerEmpty {
            get {
                return ResourceManager.GetString("RestMessageAnswerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ JSON пришел пустым, операция прекращена.
        /// </summary>
        public static string RestMessageValueEmptyJson {
            get {
                return ResourceManager.GetString("RestMessageValueEmptyJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт.
        /// </summary>
        public static string RestPort {
            get {
                return ResourceManager.GetString("RestPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        public static string RestStatusOk {
            get {
                return ResourceManager.GetString("RestStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TypeDevice.
        /// </summary>
        public static string RestTypeDevice {
            get {
                return ResourceManager.GetString("RestTypeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TypeTransfer.
        /// </summary>
        public static string RestTypeTransfer {
            get {
                return ResourceManager.GetString("RestTypeTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Позиция не найдена.
        /// </summary>
        public static string ResultMsgNoPosition {
            get {
                return ResourceManager.GetString("ResultMsgNoPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на autoLogin.
        /// </summary>
        public static string SharedAutoLogin {
            get {
                return ResourceManager.GetString("SharedAutoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на login.
        /// </summary>
        public static string SharedLogin {
            get {
                return ResourceManager.GetString("SharedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключения к сервису авторизации....
        /// </summary>
        public static string StateConnectAuth {
            get {
                return ResourceManager.GetString("StateConnectAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск пользователя....
        /// </summary>
        public static string StateSearchUser {
            get {
                return ResourceManager.GetString("StateSearchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка....
        /// </summary>
        public static string StateTextDefault {
            get {
                return ResourceManager.GetString("StateTextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход в ТСД....
        /// </summary>
        public static string StateTextInTSD {
            get {
                return ResourceManager.GetString("StateTextInTSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение....
        /// </summary>
        public static string StateTextSave {
            get {
                return ResourceManager.GetString("StateTextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получение меню и информации о пользователе....
        /// </summary>
        public static string StateUserInterface {
            get {
                return ResourceManager.GetString("StateUserInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка соединения....
        /// </summary>
        public static string StateVerifyConnectMessage {
            get {
                return ResourceManager.GetString("StateVerifyConnectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Детальная форма.
        /// </summary>
        public static string TitleDetail {
            get {
                return ResourceManager.GetString("TitleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТСД.
        /// </summary>
        public static string TitleHome {
            get {
                return ResourceManager.GetString("TitleHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смена пользователя.
        /// </summary>
        public static string TitleReselectUser {
            get {
                return ResourceManager.GetString("TitleReselectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DataBase.
        /// </summary>
        public static string TypeMethodDB {
            get {
                return ResourceManager.GetString("TypeMethodDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NUMERIC.
        /// </summary>
        public static string TypeNumeric {
            get {
                return ResourceManager.GetString("TypeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на STRING.
        /// </summary>
        public static string TypeString {
            get {
                return ResourceManager.GetString("TypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на erp/getDescrShk.
        /// </summary>
        public static string UrlGetDescr {
            get {
                return ResourceManager.GetString("UrlGetDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на erp/getmc.
        /// </summary>
        public static string UrlGetMc {
            get {
                return ResourceManager.GetString("UrlGetMc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на erp/getObjectById.
        /// </summary>
        public static string UrlGetObjectById {
            get {
                return ResourceManager.GetString("UrlGetObjectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на erp/getstatus.
        /// </summary>
        public static string UrlGetStatus {
            get {
                return ResourceManager.GetString("UrlGetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на auth/gettoken.
        /// </summary>
        public static string UrlGetToken {
            get {
                return ResourceManager.GetString("UrlGetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на actions/getuseractions.
        /// </summary>
        public static string UrlGetUser {
            get {
                return ResourceManager.GetString("UrlGetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на erp/execoper.
        /// </summary>
        public static string UrlSetData {
            get {
                return ResourceManager.GetString("UrlSetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на erp/execoperasync.
        /// </summary>
        public static string UrlSetDataAsync {
            get {
                return ResourceManager.GetString("UrlSetDataAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить БД.
        /// </summary>
        public static string XamButtonClearDb {
            get {
                return ResourceManager.GetString("XamButtonClearDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дать разрешение.
        /// </summary>
        public static string XamlButtonAcceptPermission {
            get {
                return ResourceManager.GetString("XamlButtonAcceptPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизация.
        /// </summary>
        public static string XamlButtonAuth {
            get {
                return ResourceManager.GetString("XamlButtonAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершить обработку.
        /// </summary>
        public static string XamlButtonComplitedProcessed {
            get {
                return ResourceManager.GetString("XamlButtonComplitedProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документы.
        /// </summary>
        public static string XamlButtonDocuments {
            get {
                return ResourceManager.GetString("XamlButtonDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string XamlButtonInput {
            get {
                return ResourceManager.GetString("XamlButtonInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string XamlButtonLogout {
            get {
                return ResourceManager.GetString("XamlButtonLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес сервера.
        /// </summary>
        public static string XamlLabelAddressServer {
            get {
                return ResourceManager.GetString("XamlLabelAddressServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматический вход.
        /// </summary>
        public static string XamlLabelAutoInput {
            get {
                return ResourceManager.GetString("XamlLabelAutoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Штрих-код сотрудника.
        /// </summary>
        public static string XamlLabelBarCodePerson {
            get {
                return ResourceManager.GetString("XamlLabelBarCodePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить пароль администратора.
        /// </summary>
        public static string XamlLabelChangePassAdmin {
            get {
                return ResourceManager.GetString("XamlLabelChangePassAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смена пользователя.
        /// </summary>
        public static string XamlLabelChangeUser {
            get {
                return ResourceManager.GetString("XamlLabelChangeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройства.
        /// </summary>
        public static string XamlLabelDevice {
            get {
                return ResourceManager.GetString("XamlLabelDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход в терминал.
        /// </summary>
        public static string XamlLabelInputTSD {
            get {
                return ResourceManager.GetString("XamlLabelInputTSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string XamlLabelLogin {
            get {
                return ResourceManager.GetString("XamlLabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string XamlLabelPassword {
            get {
                return ResourceManager.GetString("XamlLabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сотрудник.
        /// </summary>
        public static string XamlLabelPerson {
            get {
                return ResourceManager.GetString("XamlLabelPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Способ обмена данными.
        /// </summary>
        public static string XamlLabelSelectTransfer {
            get {
                return ResourceManager.GetString("XamlLabelSelectTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BUILD 3.0.
        /// </summary>
        public static string XamlLabelVersionApp {
            get {
                return ResourceManager.GetString("XamlLabelVersionApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для начала работы необходимо подключение к сети для авторизации....
        /// </summary>
        public static string XamlTextConnectDevice {
            get {
                return ResourceManager.GetString("XamlTextConnectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для продолжения работы в ТСД, необходимо разрешить приложению доступ к информации устройства..
        /// </summary>
        public static string XamlTextPermissionDevice {
            get {
                return ResourceManager.GetString("XamlTextPermissionDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сканируйте штрих-код....
        /// </summary>
        public static string XamlTextScanBarcode {
            get {
                return ResourceManager.GetString("XamlTextScanBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
